name: Ruby CI

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.4, 2.5, 2.6]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
      uses: ruby/setup-ruby@v1
      # uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Start mysql
      run: sudo systemctl start mysql.service
    - name: Install bundler
      run: gem install bundler:1.17.3
    - name: Install dependencies
      run: bundle install
    - name: Pre-test steps
      env:
        MYSQL_PASSWORD: root
        database_password: db_password
        MYSQL_ROOT_PASSWORD: root
        database_host: db_host
        database_name: siphon_test
        database_username: siphon_test_dba
        auth_server_id: auth_server_id
        base_auth_url: base_auth_url
        client_id: client_id
        client_secret: client_secret
        HOST_NAME: localhost
        SECRET_KEY_BASE: secret_key_base
      run: |
        cp config/secrets.yml.template config/secrets.yml
        cp config/database.yml.template config/database.yml
        mysql -uroot -p$MYSQL_PASSWORD -e 'create database siphon_test'
        RAILS_ENV=test bundle exec rake --trace db:migrate test
    - name: Run tests
      env:
        MYSQL_PASSWORD: root
        database_password: db_password
        MYSQL_ROOT_PASSWORD: root
        database_host: db_host
        database_name: siphon_test
        database_username: siphon_test_dba
        auth_server_id: auth_server_id
        base_auth_url: base_auth_url
        client_id: client_id
        client_secret: client_secret
        HOST_NAME: localhost
        SECRET_KEY_BASE: secret_key_base
      run: bundle exec rspec spec
